PACKAGES = {
    "@actions/core@2.0.1": {
        "deps": [
            {"id": "@actions/exec@2.0.0"},
            {"id": "@actions/http-client@3.0.0"},
        ],
        "integrity": "sha512-oBfqT3GwkvLlo1fjvhQLQxuwZCGTarTE5OuZ2Wg10hvhBj7LRIlF611WT4aZS6fDhO5ZKlY7lCAZTlpmyaHaeg==",
        "name": "@actions/core",
        "url": "https://registry.npmjs.org/@actions/core/-/core-2.0.1.tgz",
    },
    "@actions/exec@2.0.0": {
        "deps": [{"id": "@actions/io@2.0.0"}],
        "integrity": "sha512-k8ngrX2voJ/RIN6r9xB82NVqKpnMRtxDoiO+g3olkIUpQNqjArXrCQceduQZCQj3P3xm32pChRLqRrtXTlqhIw==",
        "name": "@actions/exec",
        "url": "https://registry.npmjs.org/@actions/exec/-/exec-2.0.0.tgz",
    },
    "@actions/github@6.0.1": {
        "deps": [
            {"id": "@actions/http-client@2.2.3"},
            {"id": "@octokit/core@5.2.2"},
            {"id": "@octokit/plugin-paginate-rest@9.2.2-8c12ecff"},
            {"id": "@octokit/plugin-rest-endpoint-methods@10.4.1-8c12ecff"},
            {"id": "@octokit/request-error@5.1.1"},
            {"id": "@octokit/request@8.4.1"},
            {"id": "undici@5.29.0"},
        ],
        "integrity": "sha512-xbZVcaqD4XnQAe35qSQqskb3SqIAfRyLBrHMd/8TuL7hJSz2QtbDwnNM8zWx4zO5l2fnGtseNE3MbEvD7BxVMw==",
        "name": "@actions/github",
        "url": "https://registry.npmjs.org/@actions/github/-/github-6.0.1.tgz",
    },
    "@actions/http-client@2.2.3": {
        "deps": [
            {"id": "tunnel@0.0.6"},
            {"id": "undici@5.29.0"},
        ],
        "integrity": "sha512-mx8hyJi/hjFvbPokCg4uRd4ZX78t+YyRPtnKWwIl+RzNaVuFpQHfmlGVfsKEJN8LwTCvL+DfVgAM04XaHkm6bA==",
        "name": "@actions/http-client",
        "url": "https://registry.npmjs.org/@actions/http-client/-/http-client-2.2.3.tgz",
    },
    "@actions/http-client@3.0.0": {
        "deps": [
            {"id": "tunnel@0.0.6"},
            {"id": "undici@5.29.0"},
        ],
        "integrity": "sha512-1s3tXAfVMSz9a4ZEBkXXRQD4QhY3+GAsWSbaYpeknPOKEeyRiU3lH+bHiLMZdo2x/fIeQ/hscL1wCkDLVM2DZQ==",
        "name": "@actions/http-client",
        "url": "https://registry.npmjs.org/@actions/http-client/-/http-client-3.0.0.tgz",
    },
    "@actions/io@2.0.0": {
        "integrity": "sha512-Jv33IN09XLO+0HS79aaODsvIRyduiF7NY/F6LYeK5oeUmrsz7aFdRphQjFoESF4jS7lMauDOttKALcpapVDIAg==",
        "name": "@actions/io",
        "url": "https://registry.npmjs.org/@actions/io/-/io-2.0.0.tgz",
    },
    "@fastify/busboy@2.1.1": {
        "integrity": "sha512-vBZP4NlzfOlerQTnba4aqZoMhE/a9HY7HRqoOPaETQcSQuWEIyZMHGfVu6w9wGtGK5fED5qRs2DteVCjOH60sA==",
        "name": "@fastify/busboy",
        "url": "https://registry.npmjs.org/@fastify/busboy/-/busboy-2.1.1.tgz",
    },
    "@isaacs/balanced-match@4.0.1": {
        "integrity": "sha512-yzMTt9lEb8Gv7zRioUilSglI0c0smZ9k5D65677DLWLtWJaXIS3CqcGyUFByYKlnUj6TkjLVs54fBl6+TiGQDQ==",
        "name": "@isaacs/balanced-match",
        "url": "https://registry.npmjs.org/@isaacs/balanced-match/-/balanced-match-4.0.1.tgz",
    },
    "@isaacs/brace-expansion@5.0.0": {
        "deps": [{"id": "@isaacs/balanced-match@4.0.1"}],
        "integrity": "sha512-ZT55BDLV0yv0RBm2czMiZ+SqCGO7AvmOM3G/w2xhVPH+te0aKgFjmBvGlL1dH+ql2tgGO3MVrbb3jCKyvpgnxA==",
        "name": "@isaacs/brace-expansion",
        "url": "https://registry.npmjs.org/@isaacs/brace-expansion/-/brace-expansion-5.0.0.tgz",
    },
    "@isaacs/fs-minipass@4.0.1": {
        "deps": [{"id": "minipass@7.1.2"}],
        "integrity": "sha512-wgm9Ehl2jpeqP3zw/7mo3kRHFp5MEDhqAdwy1fTGkHAwnkGOVsgpvQhL8B5n1qlb01jV3n/bI0ZfZp5lWA1k4w==",
        "name": "@isaacs/fs-minipass",
        "url": "https://registry.npmjs.org/@isaacs/fs-minipass/-/fs-minipass-4.0.1.tgz",
    },
    "@jridgewell/sourcemap-codec@1.5.5": {
        "integrity": "sha512-cYQ9310grqxueWbl+WuIUIaiUaDcj7WOq5fVhEljNVgRfOUhY9fy2zTvfoqWsnebh8Sl70VScFbICvJnLKB0Og==",
        "name": "@jridgewell/sourcemap-codec",
        "url": "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.5.5.tgz",
    },
    "@js-joda/core@5.6.5": {
        "integrity": "sha512-3zwefSMwHpu8iVUW8YYz227sIv6UFqO31p1Bf1ZH/Vom7CmNyUsXjDBlnNzcuhmOL1XfxZ3nvND42kR23XlbcQ==",
        "name": "@js-joda/core",
        "url": "https://registry.npmjs.org/@js-joda/core/-/core-5.6.5.tgz",
    },
    "@npmcli/agent@4.0.0": {
        "deps": [
            {"id": "agent-base@7.1.4"},
            {"id": "http-proxy-agent@7.0.2"},
            {"id": "https-proxy-agent@7.0.6"},
            {"id": "lru-cache@11.2.4"},
            {"id": "socks-proxy-agent@8.0.5"},
        ],
        "integrity": "sha512-kAQTcEN9E8ERLVg5AsGwLNoFb+oEG6engbqAU2P43gD4JEIkNGMHdVQ096FsOAAYpZPB0RSt0zgInKIAS1l5QA==",
        "name": "@npmcli/agent",
        "url": "https://registry.npmjs.org/@npmcli/agent/-/agent-4.0.0.tgz",
    },
    "@npmcli/fs@5.0.0": {
        "deps": [{"id": "semver@7.7.3"}],
        "integrity": "sha512-7OsC1gNORBEawOa5+j2pXN9vsicaIOH5cPXxoR6fJOmH6/EXpJB2CajXOu1fPRFun2m1lktEFX11+P89hqO/og==",
        "name": "@npmcli/fs",
        "url": "https://registry.npmjs.org/@npmcli/fs/-/fs-5.0.0.tgz",
    },
    "@octokit/auth-token@4.0.0": {
        "integrity": "sha512-tY/msAuJo6ARbK6SPIxZrPBms3xPbfwBrulZe0Wtr/DIY9lje2HeV1uoebShn6mx7SjCHif6EjMvoREj+gZ+SA==",
        "name": "@octokit/auth-token",
        "url": "https://registry.npmjs.org/@octokit/auth-token/-/auth-token-4.0.0.tgz",
    },
    "@octokit/auth-token@6.0.0": {
        "integrity": "sha512-P4YJBPdPSpWTQ1NU4XYdvHvXJJDxM6YwpS0FZHRgP7YFkdVxsWcpWGy/NVqlAA7PcPCnMacXlRm1y2PFZRWL/w==",
        "name": "@octokit/auth-token",
        "url": "https://registry.npmjs.org/@octokit/auth-token/-/auth-token-6.0.0.tgz",
    },
    "@octokit/core@5.2.2": {
        "deps": [
            {"id": "@octokit/auth-token@4.0.0"},
            {"id": "@octokit/graphql@7.1.1"},
            {"id": "@octokit/request-error@5.1.1"},
            {"id": "@octokit/request@8.4.1"},
            {"id": "@octokit/types@13.10.0"},
            {"id": "before-after-hook@2.2.3"},
            {"id": "universal-user-agent@6.0.1"},
        ],
        "integrity": "sha512-/g2d4sW9nUDJOMz3mabVQvOGhVa4e/BN/Um7yca9Bb2XTzPPnfTWHWQg+IsEYO7M3Vx+EXvaM/I2pJWIMun1bg==",
        "name": "@octokit/core",
        "url": "https://registry.npmjs.org/@octokit/core/-/core-5.2.2.tgz",
    },
    "@octokit/core@7.0.6": {
        "deps": [
            {"id": "@octokit/auth-token@6.0.0"},
            {"id": "@octokit/graphql@9.0.3"},
            {"id": "@octokit/request-error@7.1.0"},
            {"id": "@octokit/request@10.0.7"},
            {"id": "@octokit/types@16.0.0"},
            {"id": "before-after-hook@4.0.0"},
            {"id": "universal-user-agent@7.0.3"},
        ],
        "integrity": "sha512-DhGl4xMVFGVIyMwswXeyzdL4uXD5OGILGX5N8Y+f6W7LhC1Ze2poSNrkF/fedpVDHEEZ+PHFW0vL14I+mm8K3Q==",
        "name": "@octokit/core",
        "url": "https://registry.npmjs.org/@octokit/core/-/core-7.0.6.tgz",
    },
    "@octokit/endpoint@11.0.2": {
        "deps": [
            {"id": "@octokit/types@16.0.0"},
            {"id": "universal-user-agent@7.0.3"},
        ],
        "integrity": "sha512-4zCpzP1fWc7QlqunZ5bSEjxc6yLAlRTnDwKtgXfcI/FxxGoqedDG8V2+xJ60bV2kODqcGB+nATdtap/XYq2NZQ==",
        "name": "@octokit/endpoint",
        "url": "https://registry.npmjs.org/@octokit/endpoint/-/endpoint-11.0.2.tgz",
    },
    "@octokit/endpoint@9.0.6": {
        "deps": [
            {"id": "@octokit/types@13.10.0"},
            {"id": "universal-user-agent@6.0.1"},
        ],
        "integrity": "sha512-H1fNTMA57HbkFESSt3Y9+FBICv+0jFceJFPWDePYlR/iMGrwM5ph+Dd4XRQs+8X+PUFURLQgX9ChPfhJ/1uNQw==",
        "name": "@octokit/endpoint",
        "url": "https://registry.npmjs.org/@octokit/endpoint/-/endpoint-9.0.6.tgz",
    },
    "@octokit/graphql@7.1.1": {
        "deps": [
            {"id": "@octokit/request@8.4.1"},
            {"id": "@octokit/types@13.10.0"},
            {"id": "universal-user-agent@6.0.1"},
        ],
        "integrity": "sha512-3mkDltSfcDUoa176nlGoA32RGjeWjl3K7F/BwHwRMJUW/IteSa4bnSV8p2ThNkcIcZU2umkZWxwETSSCJf2Q7g==",
        "name": "@octokit/graphql",
        "url": "https://registry.npmjs.org/@octokit/graphql/-/graphql-7.1.1.tgz",
    },
    "@octokit/graphql@9.0.3": {
        "deps": [
            {"id": "@octokit/request@10.0.7"},
            {"id": "@octokit/types@16.0.0"},
            {"id": "universal-user-agent@7.0.3"},
        ],
        "integrity": "sha512-grAEuupr/C1rALFnXTv6ZQhFuL1D8G5y8CN04RgrO4FIPMrtm+mcZzFG7dcBm+nq+1ppNixu+Jd78aeJOYxlGA==",
        "name": "@octokit/graphql",
        "url": "https://registry.npmjs.org/@octokit/graphql/-/graphql-9.0.3.tgz",
    },
    "@octokit/openapi-types@20.0.0": {
        "integrity": "sha512-EtqRBEjp1dL/15V7WiX5LJMIxxkdiGJnabzYx5Apx4FkQIFgAfKumXeYAqqJCj1s+BMX4cPFIFC4OLCR6stlnA==",
        "name": "@octokit/openapi-types",
        "url": "https://registry.npmjs.org/@octokit/openapi-types/-/openapi-types-20.0.0.tgz",
    },
    "@octokit/openapi-types@24.2.0": {
        "integrity": "sha512-9sIH3nSUttelJSXUrmGzl7QUBFul0/mB8HRYl3fOlgHbIWG+WnYDXU3v/2zMtAvuzZ/ed00Ei6on975FhBfzrg==",
        "name": "@octokit/openapi-types",
        "url": "https://registry.npmjs.org/@octokit/openapi-types/-/openapi-types-24.2.0.tgz",
    },
    "@octokit/openapi-types@27.0.0": {
        "integrity": "sha512-whrdktVs1h6gtR+09+QsNk2+FO+49j6ga1c55YZudfEG+oKJVvJLQi3zkOm5JjiUXAagWK2tI2kTGKJ2Ys7MGA==",
        "name": "@octokit/openapi-types",
        "url": "https://registry.npmjs.org/@octokit/openapi-types/-/openapi-types-27.0.0.tgz",
    },
    "@octokit/plugin-paginate-rest@14.0.0-71a3a269": {
        "deps": [
            {"id": "@octokit/core@7.0.6"},
            {"id": "@octokit/types@16.0.0"},
        ],
        "integrity": "sha512-fNVRE7ufJiAA3XUrha2omTA39M6IXIc6GIZLvlbsm8QOQCYvpq/LkMNGyFlB1d8hTDzsAXa3OKtybdMAYsV/fw==",
        "name": "@octokit/plugin-paginate-rest",
        "url": "https://registry.npmjs.org/@octokit/plugin-paginate-rest/-/plugin-paginate-rest-14.0.0.tgz",
    },
    "@octokit/plugin-paginate-rest@9.2.2-8c12ecff": {
        "deps": [
            {"id": "@octokit/core@5.2.2"},
            {"id": "@octokit/types@12.6.0"},
        ],
        "integrity": "sha512-u3KYkGF7GcZnSD/3UP0S7K5XUFT2FkOQdcfXZGZQPGv3lm4F2Xbf71lvjldr8c1H3nNbF+33cLEkWYbokGWqiQ==",
        "name": "@octokit/plugin-paginate-rest",
        "url": "https://registry.npmjs.org/@octokit/plugin-paginate-rest/-/plugin-paginate-rest-9.2.2.tgz",
    },
    "@octokit/plugin-request-log@6.0.0-71a3a269": {
        "deps": [{"id": "@octokit/core@7.0.6"}],
        "integrity": "sha512-UkOzeEN3W91/eBq9sPZNQ7sUBvYCqYbrrD8gTbBuGtHEuycE4/awMXcYvx6sVYo7LypPhmQwwpUe4Yyu4QZN5Q==",
        "name": "@octokit/plugin-request-log",
        "url": "https://registry.npmjs.org/@octokit/plugin-request-log/-/plugin-request-log-6.0.0.tgz",
    },
    "@octokit/plugin-rest-endpoint-methods@10.4.1-8c12ecff": {
        "deps": [
            {"id": "@octokit/core@5.2.2"},
            {"id": "@octokit/types@12.6.0"},
        ],
        "integrity": "sha512-xV1b+ceKV9KytQe3zCVqjg+8GTGfDYwaT1ATU5isiUyVtlVAO3HNdzpS4sr4GBx4hxQ46s7ITtZrAsxG22+rVg==",
        "name": "@octokit/plugin-rest-endpoint-methods",
        "url": "https://registry.npmjs.org/@octokit/plugin-rest-endpoint-methods/-/plugin-rest-endpoint-methods-10.4.1.tgz",
    },
    "@octokit/plugin-rest-endpoint-methods@17.0.0-71a3a269": {
        "deps": [
            {"id": "@octokit/core@7.0.6"},
            {"id": "@octokit/types@16.0.0"},
        ],
        "integrity": "sha512-B5yCyIlOJFPqUUeiD0cnBJwWJO8lkJs5d8+ze9QDP6SvfiXSz1BF+91+0MeI1d2yxgOhU/O+CvtiZ9jSkHhFAw==",
        "name": "@octokit/plugin-rest-endpoint-methods",
        "url": "https://registry.npmjs.org/@octokit/plugin-rest-endpoint-methods/-/plugin-rest-endpoint-methods-17.0.0.tgz",
    },
    "@octokit/request-error@5.1.1": {
        "deps": [
            {"id": "@octokit/types@13.10.0"},
            {"id": "deprecation@2.3.1"},
            {"id": "once@1.4.0"},
        ],
        "integrity": "sha512-v9iyEQJH6ZntoENr9/yXxjuezh4My67CBSu9r6Ve/05Iu5gNgnisNWOsoJHTP6k0Rr0+HQIpnH+kyammu90q/g==",
        "name": "@octokit/request-error",
        "url": "https://registry.npmjs.org/@octokit/request-error/-/request-error-5.1.1.tgz",
    },
    "@octokit/request-error@7.1.0": {
        "deps": [{"id": "@octokit/types@16.0.0"}],
        "integrity": "sha512-KMQIfq5sOPpkQYajXHwnhjCC0slzCNScLHs9JafXc4RAJI+9f+jNDlBNaIMTvazOPLgb4BnlhGJOTbnN0wIjPw==",
        "name": "@octokit/request-error",
        "url": "https://registry.npmjs.org/@octokit/request-error/-/request-error-7.1.0.tgz",
    },
    "@octokit/request@10.0.7": {
        "deps": [
            {"id": "@octokit/endpoint@11.0.2"},
            {"id": "@octokit/request-error@7.1.0"},
            {"id": "@octokit/types@16.0.0"},
            {"id": "fast-content-type-parse@3.0.0"},
            {"id": "universal-user-agent@7.0.3"},
        ],
        "integrity": "sha512-v93h0i1yu4idj8qFPZwjehoJx4j3Ntn+JhXsdJrG9pYaX6j/XRz2RmasMUHtNgQD39nrv/VwTWSqK0RNXR8upA==",
        "name": "@octokit/request",
        "url": "https://registry.npmjs.org/@octokit/request/-/request-10.0.7.tgz",
    },
    "@octokit/request@8.4.1": {
        "deps": [
            {"id": "@octokit/endpoint@9.0.6"},
            {"id": "@octokit/request-error@5.1.1"},
            {"id": "@octokit/types@13.10.0"},
            {"id": "universal-user-agent@6.0.1"},
        ],
        "integrity": "sha512-qnB2+SY3hkCmBxZsR/MPCybNmbJe4KAlfWErXq+rBKkQJlbjdJeS85VI9r8UqeLYLvnAenU8Q1okM/0MBsAGXw==",
        "name": "@octokit/request",
        "url": "https://registry.npmjs.org/@octokit/request/-/request-8.4.1.tgz",
    },
    "@octokit/rest@22.0.1": {
        "deps": [
            {"id": "@octokit/core@7.0.6"},
            {"id": "@octokit/plugin-paginate-rest@14.0.0-71a3a269"},
            {"id": "@octokit/plugin-request-log@6.0.0-71a3a269"},
            {"id": "@octokit/plugin-rest-endpoint-methods@17.0.0-71a3a269"},
        ],
        "integrity": "sha512-Jzbhzl3CEexhnivb1iQ0KJ7s5vvjMWcmRtq5aUsKmKDrRW6z3r84ngmiFKFvpZjpiU/9/S6ITPFRpn5s/3uQJw==",
        "name": "@octokit/rest",
        "url": "https://registry.npmjs.org/@octokit/rest/-/rest-22.0.1.tgz",
    },
    "@octokit/types@12.6.0": {
        "deps": [{"id": "@octokit/openapi-types@20.0.0"}],
        "integrity": "sha512-1rhSOfRa6H9w4YwK0yrf5faDaDTb+yLyBUKOCV4xtCDB5VmIPqd/v9yr9o6SAzOAlRxMiRiCic6JVM1/kunVkw==",
        "name": "@octokit/types",
        "url": "https://registry.npmjs.org/@octokit/types/-/types-12.6.0.tgz",
    },
    "@octokit/types@13.10.0": {
        "deps": [{"id": "@octokit/openapi-types@24.2.0"}],
        "integrity": "sha512-ifLaO34EbbPj0Xgro4G5lP5asESjwHracYJvVaPIyXMuiuXLlhic3S47cBdTb+jfODkTE5YtGCLt3Ay3+J97sA==",
        "name": "@octokit/types",
        "url": "https://registry.npmjs.org/@octokit/types/-/types-13.10.0.tgz",
    },
    "@octokit/types@16.0.0": {
        "deps": [{"id": "@octokit/openapi-types@27.0.0"}],
        "integrity": "sha512-sKq+9r1Mm4efXW1FCk7hFSeJo4QKreL/tTbR0rz/qx/r1Oa2VV83LTA/H/MuCOX7uCIJmQVRKBcbmWoySjAnSg==",
        "name": "@octokit/types",
        "url": "https://registry.npmjs.org/@octokit/types/-/types-16.0.0.tgz",
    },
    "@rollup/plugin-commonjs@29.0.0-dc3fc578": {
        "deps": [
            {"id": "@rollup/pluginutils@5.3.0-1b456630"},
            {"id": "commondir@1.0.1"},
            {"id": "estree-walker@2.0.2"},
            {"id": "fdir@6.5.0-0e783aad"},
            {"id": "is-reference@1.2.1"},
            {"id": "magic-string@0.30.21"},
            {"id": "picomatch@4.0.3"},
            {"id": "rollup@4.53.3"},
        ],
        "integrity": "sha512-U2YHaxR2cU/yAiwKJtJRhnyLk7cifnQw0zUpISsocBDoHDJn+HTV74ABqnwr5bEgWUwFZC9oFL6wLe21lHu5eQ==",
        "name": "@rollup/plugin-commonjs",
        "url": "https://registry.npmjs.org/@rollup/plugin-commonjs/-/plugin-commonjs-29.0.0.tgz",
    },
    "@rollup/plugin-json@6.1.0-dc3fc578": {
        "deps": [
            {"id": "@rollup/pluginutils@5.3.0-1b456630"},
            {"id": "rollup@4.53.3"},
        ],
        "integrity": "sha512-EGI2te5ENk1coGeADSIwZ7G2Q8CJS2sF120T7jLw4xFw9n7wIOXHo+kIYRAoVpJAN+kmqZSoO3Fp4JtoNF4ReA==",
        "name": "@rollup/plugin-json",
        "url": "https://registry.npmjs.org/@rollup/plugin-json/-/plugin-json-6.1.0.tgz",
    },
    "@rollup/plugin-node-resolve@16.0.3-dc3fc578": {
        "deps": [
            {"id": "@rollup/pluginutils@5.3.0-1b456630"},
            {"id": "@types/resolve@1.20.2"},
            {"id": "deepmerge@4.3.1"},
            {"id": "is-module@1.0.0"},
            {"id": "resolve@1.22.11-4e481dbf"},
            {"id": "rollup@4.53.3"},
        ],
        "integrity": "sha512-lUYM3UBGuM93CnMPG1YocWu7X802BrNF3jW2zny5gQyLQgRFJhV1Sq0Zi74+dh/6NBx1DxFC4b4GXg9wUCG5Qg==",
        "name": "@rollup/plugin-node-resolve",
        "url": "https://registry.npmjs.org/@rollup/plugin-node-resolve/-/plugin-node-resolve-16.0.3.tgz",
    },
    "@rollup/pluginutils@5.3.0-1b456630": {
        "deps": [
            {"id": "@types/estree@1.0.8"},
            {"id": "estree-walker@2.0.2"},
            {"id": "picomatch@4.0.3"},
            {"id": "rollup@4.53.3"},
        ],
        "integrity": "sha512-5EdhGZtnu3V88ces7s53hhfK5KSASnJZv8Lulpc04cWO3REESroJXg73DFsOmgbU2BhwV0E20bu2IDZb3VKW4Q==",
        "name": "@rollup/pluginutils",
        "url": "https://registry.npmjs.org/@rollup/pluginutils/-/pluginutils-5.3.0.tgz",
    },
    "@rollup/rollup-android-arm-eabi@4.53.3": {
        "arch": ["arm"],
        "os": ["android"],
        "integrity": "sha512-mRSi+4cBjrRLoaal2PnqH82Wqyb+d3HsPUN/W+WslCXsZsyHa9ZeQQX/pQsZaVIWDkPcpV6jJ+3KLbTbgnwv8w==",
        "name": "@rollup/rollup-android-arm-eabi",
        "url": "https://registry.npmjs.org/@rollup/rollup-android-arm-eabi/-/rollup-android-arm-eabi-4.53.3.tgz",
    },
    "@rollup/rollup-android-arm64@4.53.3": {
        "arch": ["arm64"],
        "os": ["android"],
        "integrity": "sha512-CbDGaMpdE9sh7sCmTrTUyllhrg65t6SwhjlMJsLr+J8YjFuPmCEjbBSx4Z/e4SmDyH3aB5hGaJUP2ltV/vcs4w==",
        "name": "@rollup/rollup-android-arm64",
        "url": "https://registry.npmjs.org/@rollup/rollup-android-arm64/-/rollup-android-arm64-4.53.3.tgz",
    },
    "@rollup/rollup-darwin-arm64@4.53.3": {
        "arch": ["arm64"],
        "os": ["darwin"],
        "integrity": "sha512-Nr7SlQeqIBpOV6BHHGZgYBuSdanCXuw09hon14MGOLGmXAFYjx1wNvquVPmpZnl0tLjg25dEdr4IQ6GgyToCUA==",
        "name": "@rollup/rollup-darwin-arm64",
        "url": "https://registry.npmjs.org/@rollup/rollup-darwin-arm64/-/rollup-darwin-arm64-4.53.3.tgz",
    },
    "@rollup/rollup-darwin-x64@4.53.3": {
        "arch": ["x64"],
        "os": ["darwin"],
        "integrity": "sha512-DZ8N4CSNfl965CmPktJ8oBnfYr3F8dTTNBQkRlffnUarJ2ohudQD17sZBa097J8xhQ26AwhHJ5mvUyQW8ddTsQ==",
        "name": "@rollup/rollup-darwin-x64",
        "url": "https://registry.npmjs.org/@rollup/rollup-darwin-x64/-/rollup-darwin-x64-4.53.3.tgz",
    },
    "@rollup/rollup-freebsd-arm64@4.53.3": {
        "arch": ["arm64"],
        "os": ["freebsd"],
        "integrity": "sha512-yMTrCrK92aGyi7GuDNtGn2sNW+Gdb4vErx4t3Gv/Tr+1zRb8ax4z8GWVRfr3Jw8zJWvpGHNpss3vVlbF58DZ4w==",
        "name": "@rollup/rollup-freebsd-arm64",
        "url": "https://registry.npmjs.org/@rollup/rollup-freebsd-arm64/-/rollup-freebsd-arm64-4.53.3.tgz",
    },
    "@rollup/rollup-freebsd-x64@4.53.3": {
        "arch": ["x64"],
        "os": ["freebsd"],
        "integrity": "sha512-lMfF8X7QhdQzseM6XaX0vbno2m3hlyZFhwcndRMw8fbAGUGL3WFMBdK0hbUBIUYcEcMhVLr1SIamDeuLBnXS+Q==",
        "name": "@rollup/rollup-freebsd-x64",
        "url": "https://registry.npmjs.org/@rollup/rollup-freebsd-x64/-/rollup-freebsd-x64-4.53.3.tgz",
    },
    "@rollup/rollup-linux-arm-gnueabihf@4.53.3": {
        "arch": ["arm"],
        "libc": ["glibc"],
        "os": ["linux"],
        "integrity": "sha512-k9oD15soC/Ln6d2Wv/JOFPzZXIAIFLp6B+i14KhxAfnq76ajt0EhYc5YPeX6W1xJkAdItcVT+JhKl1QZh44/qw==",
        "name": "@rollup/rollup-linux-arm-gnueabihf",
        "url": "https://registry.npmjs.org/@rollup/rollup-linux-arm-gnueabihf/-/rollup-linux-arm-gnueabihf-4.53.3.tgz",
    },
    "@rollup/rollup-linux-arm-musleabihf@4.53.3": {
        "arch": ["arm"],
        "libc": ["musl"],
        "os": ["linux"],
        "integrity": "sha512-vTNlKq+N6CK/8UktsrFuc+/7NlEYVxgaEgRXVUVK258Z5ymho29skzW1sutgYjqNnquGwVUObAaxae8rZ6YMhg==",
        "name": "@rollup/rollup-linux-arm-musleabihf",
        "url": "https://registry.npmjs.org/@rollup/rollup-linux-arm-musleabihf/-/rollup-linux-arm-musleabihf-4.53.3.tgz",
    },
    "@rollup/rollup-linux-arm64-gnu@4.53.3": {
        "arch": ["arm64"],
        "libc": ["glibc"],
        "os": ["linux"],
        "integrity": "sha512-RGrFLWgMhSxRs/EWJMIFM1O5Mzuz3Xy3/mnxJp/5cVhZ2XoCAxJnmNsEyeMJtpK+wu0FJFWz+QF4mjCA7AUQ3w==",
        "name": "@rollup/rollup-linux-arm64-gnu",
        "url": "https://registry.npmjs.org/@rollup/rollup-linux-arm64-gnu/-/rollup-linux-arm64-gnu-4.53.3.tgz",
    },
    "@rollup/rollup-linux-arm64-musl@4.53.3": {
        "arch": ["arm64"],
        "libc": ["musl"],
        "os": ["linux"],
        "integrity": "sha512-kASyvfBEWYPEwe0Qv4nfu6pNkITLTb32p4yTgzFCocHnJLAHs+9LjUu9ONIhvfT/5lv4YS5muBHyuV84epBo/A==",
        "name": "@rollup/rollup-linux-arm64-musl",
        "url": "https://registry.npmjs.org/@rollup/rollup-linux-arm64-musl/-/rollup-linux-arm64-musl-4.53.3.tgz",
    },
    "@rollup/rollup-linux-loong64-gnu@4.53.3": {
        "arch": ["loong64"],
        "libc": ["glibc"],
        "os": ["linux"],
        "integrity": "sha512-JiuKcp2teLJwQ7vkJ95EwESWkNRFJD7TQgYmCnrPtlu50b4XvT5MOmurWNrCj3IFdyjBQ5p9vnrX4JM6I8OE7g==",
        "name": "@rollup/rollup-linux-loong64-gnu",
        "url": "https://registry.npmjs.org/@rollup/rollup-linux-loong64-gnu/-/rollup-linux-loong64-gnu-4.53.3.tgz",
    },
    "@rollup/rollup-linux-ppc64-gnu@4.53.3": {
        "arch": ["ppc64"],
        "libc": ["glibc"],
        "os": ["linux"],
        "integrity": "sha512-EoGSa8nd6d3T7zLuqdojxC20oBfNT8nexBbB/rkxgKj5T5vhpAQKKnD+h3UkoMuTyXkP5jTjK/ccNRmQrPNDuw==",
        "name": "@rollup/rollup-linux-ppc64-gnu",
        "url": "https://registry.npmjs.org/@rollup/rollup-linux-ppc64-gnu/-/rollup-linux-ppc64-gnu-4.53.3.tgz",
    },
    "@rollup/rollup-linux-riscv64-gnu@4.53.3": {
        "arch": ["riscv64"],
        "libc": ["glibc"],
        "os": ["linux"],
        "integrity": "sha512-4s+Wped2IHXHPnAEbIB0YWBv7SDohqxobiiPA1FIWZpX+w9o2i4LezzH/NkFUl8LRci/8udci6cLq+jJQlh+0g==",
        "name": "@rollup/rollup-linux-riscv64-gnu",
        "url": "https://registry.npmjs.org/@rollup/rollup-linux-riscv64-gnu/-/rollup-linux-riscv64-gnu-4.53.3.tgz",
    },
    "@rollup/rollup-linux-riscv64-musl@4.53.3": {
        "arch": ["riscv64"],
        "libc": ["musl"],
        "os": ["linux"],
        "integrity": "sha512-68k2g7+0vs2u9CxDt5ktXTngsxOQkSEV/xBbwlqYcUrAVh6P9EgMZvFsnHy4SEiUl46Xf0IObWVbMvPrr2gw8A==",
        "name": "@rollup/rollup-linux-riscv64-musl",
        "url": "https://registry.npmjs.org/@rollup/rollup-linux-riscv64-musl/-/rollup-linux-riscv64-musl-4.53.3.tgz",
    },
    "@rollup/rollup-linux-s390x-gnu@4.53.3": {
        "arch": ["s390x"],
        "libc": ["glibc"],
        "os": ["linux"],
        "integrity": "sha512-VYsFMpULAz87ZW6BVYw3I6sWesGpsP9OPcyKe8ofdg9LHxSbRMd7zrVrr5xi/3kMZtpWL/wC+UIJWJYVX5uTKg==",
        "name": "@rollup/rollup-linux-s390x-gnu",
        "url": "https://registry.npmjs.org/@rollup/rollup-linux-s390x-gnu/-/rollup-linux-s390x-gnu-4.53.3.tgz",
    },
    "@rollup/rollup-linux-x64-gnu@4.53.3": {
        "arch": ["x64"],
        "libc": ["glibc"],
        "os": ["linux"],
        "integrity": "sha512-3EhFi1FU6YL8HTUJZ51imGJWEX//ajQPfqWLI3BQq4TlvHy4X0MOr5q3D2Zof/ka0d5FNdPwZXm3Yyib/UEd+w==",
        "name": "@rollup/rollup-linux-x64-gnu",
        "url": "https://registry.npmjs.org/@rollup/rollup-linux-x64-gnu/-/rollup-linux-x64-gnu-4.53.3.tgz",
    },
    "@rollup/rollup-linux-x64-musl@4.53.3": {
        "arch": ["x64"],
        "libc": ["musl"],
        "os": ["linux"],
        "integrity": "sha512-eoROhjcc6HbZCJr+tvVT8X4fW3/5g/WkGvvmwz/88sDtSJzO7r/blvoBDgISDiCjDRZmHpwud7h+6Q9JxFwq1Q==",
        "name": "@rollup/rollup-linux-x64-musl",
        "url": "https://registry.npmjs.org/@rollup/rollup-linux-x64-musl/-/rollup-linux-x64-musl-4.53.3.tgz",
    },
    "@rollup/rollup-openharmony-arm64@4.53.3": {
        "arch": ["arm64"],
        "os": ["openharmony"],
        "integrity": "sha512-OueLAWgrNSPGAdUdIjSWXw+u/02BRTcnfw9PN41D2vq/JSEPnJnVuBgw18VkN8wcd4fjUs+jFHVM4t9+kBSNLw==",
        "name": "@rollup/rollup-openharmony-arm64",
        "url": "https://registry.npmjs.org/@rollup/rollup-openharmony-arm64/-/rollup-openharmony-arm64-4.53.3.tgz",
    },
    "@rollup/rollup-win32-arm64-msvc@4.53.3": {
        "arch": ["arm64"],
        "os": ["win32"],
        "integrity": "sha512-GOFuKpsxR/whszbF/bzydebLiXIHSgsEUp6M0JI8dWvi+fFa1TD6YQa4aSZHtpmh2/uAlj/Dy+nmby3TJ3pkTw==",
        "name": "@rollup/rollup-win32-arm64-msvc",
        "url": "https://registry.npmjs.org/@rollup/rollup-win32-arm64-msvc/-/rollup-win32-arm64-msvc-4.53.3.tgz",
    },
    "@rollup/rollup-win32-ia32-msvc@4.53.3": {
        "arch": ["ia32"],
        "os": ["win32"],
        "integrity": "sha512-iah+THLcBJdpfZ1TstDFbKNznlzoxa8fmnFYK4V67HvmuNYkVdAywJSoteUszvBQ9/HqN2+9AZghbajMsFT+oA==",
        "name": "@rollup/rollup-win32-ia32-msvc",
        "url": "https://registry.npmjs.org/@rollup/rollup-win32-ia32-msvc/-/rollup-win32-ia32-msvc-4.53.3.tgz",
    },
    "@rollup/rollup-win32-x64-gnu@4.53.3": {
        "arch": ["x64"],
        "os": ["win32"],
        "integrity": "sha512-J9QDiOIZlZLdcot5NXEepDkstocktoVjkaKUtqzgzpt2yWjGlbYiKyp05rWwk4nypbYUNoFAztEgixoLaSETkg==",
        "name": "@rollup/rollup-win32-x64-gnu",
        "url": "https://registry.npmjs.org/@rollup/rollup-win32-x64-gnu/-/rollup-win32-x64-gnu-4.53.3.tgz",
    },
    "@rollup/rollup-win32-x64-msvc@4.53.3": {
        "arch": ["x64"],
        "os": ["win32"],
        "integrity": "sha512-UhTd8u31dXadv0MopwGgNOBpUVROFKWVQgAg5N1ESyCz8AuBcMqm4AuTjrwgQKGDfoFuz02EuMRHQIw/frmYKQ==",
        "name": "@rollup/rollup-win32-x64-msvc",
        "url": "https://registry.npmjs.org/@rollup/rollup-win32-x64-msvc/-/rollup-win32-x64-msvc-4.53.3.tgz",
    },
    "@types/estree@1.0.8": {
        "integrity": "sha512-dWHzHa2WqEXI/O1E9OjrocMTKJl2mSrEolh1Iomrv6U+JuNwaHXsXx9bLu5gG7BUWFIN0skIQJQ/L1rIex4X6w==",
        "name": "@types/estree",
        "url": "https://registry.npmjs.org/@types/estree/-/estree-1.0.8.tgz",
    },
    "@types/node@24.10.4": {
        "deps": [{"id": "undici-types@7.16.0"}],
        "integrity": "sha512-vnDVpYPMzs4wunl27jHrfmwojOGKya0xyM3sH+UE5iv5uPS6vX7UIoh6m+vQc5LGBq52HBKPIn/zcSZVzeDEZg==",
        "name": "@types/node",
        "url": "https://registry.npmjs.org/@types/node/-/node-24.10.4.tgz",
    },
    "@types/resolve@1.20.2": {
        "integrity": "sha512-60BCwRFOZCQhDncwQdxxeOEEkbc5dIMccYLwbxsS4TUNeVECQ/pBJ0j09mrHOl/JJvpRPGwO9SvE4nR2Nb/a4Q==",
        "name": "@types/resolve",
        "url": "https://registry.npmjs.org/@types/resolve/-/resolve-1.20.2.tgz",
    },
    "abbrev@4.0.0": {
        "integrity": "sha512-a1wflyaL0tHtJSmLSOVybYhy22vRih4eduhhrkcjgrWGnRfrZtovJ2FRjxuTtkkj47O/baf0R86QU5OuYpz8fA==",
        "name": "abbrev",
        "url": "https://registry.npmjs.org/abbrev/-/abbrev-4.0.0.tgz",
    },
    "agent-base@7.1.4": {
        "integrity": "sha512-MnA+YT8fwfJPgBx3m60MNqakm30XOkyIoH1y6huTQvC0PwZG7ki8NacLBcrPbNoo8vEZy7Jpuk7+jMO+CUovTQ==",
        "name": "agent-base",
        "url": "https://registry.npmjs.org/agent-base/-/agent-base-7.1.4.tgz",
    },
    "before-after-hook@2.2.3": {
        "integrity": "sha512-NzUnlZexiaH/46WDhANlyR2bXRopNg4F/zuSA3OpZnllCUgRaOF2znDioDWrmbNVsuZk6l9pMquQB38cfBZwkQ==",
        "name": "before-after-hook",
        "url": "https://registry.npmjs.org/before-after-hook/-/before-after-hook-2.2.3.tgz",
    },
    "before-after-hook@4.0.0": {
        "integrity": "sha512-q6tR3RPqIB1pMiTRMFcZwuG5T8vwp+vUvEG0vuI6B+Rikh5BfPp2fQ82c925FOs+b0lcFQ8CFrL+KbilfZFhOQ==",
        "name": "before-after-hook",
        "url": "https://registry.npmjs.org/before-after-hook/-/before-after-hook-4.0.0.tgz",
    },
    "cacache@20.0.3": {
        "deps": [
            {"id": "@npmcli/fs@5.0.0"},
            {"id": "fs-minipass@3.0.3"},
            {"id": "glob@13.0.0"},
            {"id": "lru-cache@11.2.4"},
            {"id": "minipass-collect@2.0.1"},
            {"id": "minipass-flush@1.0.5"},
            {"id": "minipass-pipeline@1.2.4"},
            {"id": "minipass@7.1.2"},
            {"id": "p-map@7.0.4"},
            {"id": "ssri@13.0.0"},
            {"id": "unique-filename@5.0.0"},
        ],
        "integrity": "sha512-3pUp4e8hv07k1QlijZu6Kn7c9+ZpWWk4j3F8N3xPuCExULobqJydKYOTj1FTq58srkJsXvO7LbGAH4C0ZU3WGw==",
        "name": "cacache",
        "url": "https://registry.npmjs.org/cacache/-/cacache-20.0.3.tgz",
    },
    "chownr@3.0.0": {
        "integrity": "sha512-+IxzY9BZOQd/XuYPRmrvEVjF/nqj5kgT4kEq7VofrDoM1MxoRjEWkrCC3EtLi59TVawxTAn+orJwFQcrqEN1+g==",
        "name": "chownr",
        "url": "https://registry.npmjs.org/chownr/-/chownr-3.0.0.tgz",
    },
    "commondir@1.0.1": {
        "integrity": "sha512-W9pAhw0ja1Edb5GVdIF1mjZw/ASI0AlShXM83UUGe2DVr5TdAPEA1OA8m/g8zWp9x6On7gqufY+FatDbC3MDQg==",
        "name": "commondir",
        "url": "https://registry.npmjs.org/commondir/-/commondir-1.0.1.tgz",
    },
    "debug@4.4.3-643ed7cc": {
        "deps": [{"id": "ms@2.1.3"}],
        "integrity": "sha512-RGwwWnwQvkVfavKVt22FGLw+xYSdzARwm0ru6DhTVA3umU5hZc28V3kO4stgYryrTlLpuvgI9GiijltAjNbcqA==",
        "name": "debug",
        "url": "https://registry.npmjs.org/debug/-/debug-4.4.3.tgz",
    },
    "deepmerge@4.3.1": {
        "integrity": "sha512-3sUqbMEc77XqpdNO7FRyRog+eW3ph+GYCbj+rK+uYyRMuwsVy0rMiVtPn+QJlKFvWP/1PYpapqYn0Me2knFn+A==",
        "name": "deepmerge",
        "url": "https://registry.npmjs.org/deepmerge/-/deepmerge-4.3.1.tgz",
    },
    "deprecation@2.3.1": {
        "integrity": "sha512-xmHIy4F3scKVwMsQ4WnVaS8bHOx0DmVwRywosKhaILI0ywMDWPtBSku2HNxRvF7jtwDRsoEwYQSfbxj8b7RlJQ==",
        "name": "deprecation",
        "url": "https://registry.npmjs.org/deprecation/-/deprecation-2.3.1.tgz",
    },
    "encoding@0.1.13": {
        "deps": [{"id": "iconv-lite@0.6.3"}],
        "integrity": "sha512-ETBauow1T35Y/WZMkio9jiM0Z5xjHHmJ4XmjZOq1l/dXz3lr2sRn87nJy20RupqSh1F2m3HHPSp8ShIPQJrJ3A==",
        "name": "encoding",
        "url": "https://registry.npmjs.org/encoding/-/encoding-0.1.13.tgz",
    },
    "env-paths@2.2.1": {
        "integrity": "sha512-+h1lkLKhZMTYjog1VEpJNG7NZJWcuc2DDk/qsqSTRRCOXiLjeQ1d1/udrUGhqMxUgAlwKNZ0cf2uqan5GLuS2A==",
        "name": "env-paths",
        "url": "https://registry.npmjs.org/env-paths/-/env-paths-2.2.1.tgz",
    },
    "err-code@2.0.3": {
        "integrity": "sha512-2bmlRpNKBxT/CRmPOlyISQpNj+qSeYvcym/uT0Jx2bMOlKLtSy1ZmLuVxSEKKyor/N5yhvp/ZiG1oE3DEYMSFA==",
        "name": "err-code",
        "url": "https://registry.npmjs.org/err-code/-/err-code-2.0.3.tgz",
    },
    "estree-walker@2.0.2": {
        "integrity": "sha512-Rfkk/Mp/DL7JVje3u18FxFujQlTNR2q6QfMSMB7AvCBx91NGj/ba3kCfza0f6dVDbw7YlRf/nDrn7pQrCCyQ/w==",
        "name": "estree-walker",
        "url": "https://registry.npmjs.org/estree-walker/-/estree-walker-2.0.2.tgz",
    },
    "exponential-backoff@3.1.3": {
        "integrity": "sha512-ZgEeZXj30q+I0EN+CbSSpIyPaJ5HVQD18Z1m+u1FXbAeT94mr1zw50q4q6jiiC447Nl/YTcIYSAftiGqetwXCA==",
        "name": "exponential-backoff",
        "url": "https://registry.npmjs.org/exponential-backoff/-/exponential-backoff-3.1.3.tgz",
    },
    "fast-content-type-parse@3.0.0": {
        "integrity": "sha512-ZvLdcY8P+N8mGQJahJV5G4U88CSvT1rP8ApL6uETe88MBXrBHAkZlSEySdUlyztF7ccb+Znos3TFqaepHxdhBg==",
        "name": "fast-content-type-parse",
        "url": "https://registry.npmjs.org/fast-content-type-parse/-/fast-content-type-parse-3.0.0.tgz",
    },
    "fdir@6.5.0-0e783aad": {
        "deps": [{"id": "picomatch@4.0.3"}],
        "integrity": "sha512-tIbYtZbucOs0BRGqPJkshJUYdL+SDH7dVM8gjy+ERp3WAUjLEFJE+02kanyHtwjWOnwrKYBiwAmM0p4kLJAnXg==",
        "name": "fdir",
        "url": "https://registry.npmjs.org/fdir/-/fdir-6.5.0.tgz",
    },
    "fs-minipass@3.0.3": {
        "deps": [{"id": "minipass@7.1.2"}],
        "integrity": "sha512-XUBA9XClHbnJWSfBzjkm6RvPsyg3sryZt06BEQoXcF7EK/xpGaQYJgQKDJSUH5SGZ76Y7pFx1QBnXz09rU5Fbw==",
        "name": "fs-minipass",
        "url": "https://registry.npmjs.org/fs-minipass/-/fs-minipass-3.0.3.tgz",
    },
    "fsevents@2.3.3-21ad2b13": {
        "os": ["darwin"],
        "deps": [{"id": "node-gyp@12.1.0"}],
        "integrity": "sha512-5xoDfX+fL7faATnagmWPpbFtwh/R77WmMMqqHGS65C3vvB0YHrgF+B1YmZ3441tMj5n63k0212XNoJwzlhffQw==",
        "name": "fsevents",
        "url": "https://registry.npmjs.org/fsevents/-/fsevents-2.3.3.tgz",
    },
    "function-bind@1.1.2": {
        "integrity": "sha512-7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==",
        "name": "function-bind",
        "url": "https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz",
    },
    "glob@13.0.0": {
        "deps": [
            {"id": "minimatch@10.1.1"},
            {"id": "minipass@7.1.2"},
            {"id": "path-scurry@2.0.1"},
        ],
        "integrity": "sha512-tvZgpqk6fz4BaNZ66ZsRaZnbHvP/jG3uKJvAZOwEVUL4RTA5nJeeLYfyN9/VA8NX/V3IBG+hkeuGpKjvELkVhA==",
        "name": "glob",
        "url": "https://registry.npmjs.org/glob/-/glob-13.0.0.tgz",
    },
    "graceful-fs@4.2.11": {
        "integrity": "sha512-RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==",
        "name": "graceful-fs",
        "url": "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz",
    },
    "hasown@2.0.2": {
        "deps": [{"id": "function-bind@1.1.2"}],
        "integrity": "sha512-0hJU9SCPvmMzIBdZFqNPXWa6dqh7WdH0cII9y+CyS8rG3nL48Bclra9HmKhVVUHyPWNH5Y7xDwAB7bfgSjkUMQ==",
        "name": "hasown",
        "url": "https://registry.npmjs.org/hasown/-/hasown-2.0.2.tgz",
    },
    "http-cache-semantics@4.2.0": {
        "integrity": "sha512-dTxcvPXqPvXBQpq5dUr6mEMJX4oIEFv6bwom3FDwKRDsuIjjJGANqhBuoAn9c1RQJIdAKav33ED65E2ys+87QQ==",
        "name": "http-cache-semantics",
        "url": "https://registry.npmjs.org/http-cache-semantics/-/http-cache-semantics-4.2.0.tgz",
    },
    "http-proxy-agent@7.0.2": {
        "deps": [
            {"id": "agent-base@7.1.4"},
            {"id": "debug@4.4.3-643ed7cc"},
        ],
        "integrity": "sha512-T1gkAiYYDWYx3V5Bmyu7HcfcvL7mUrTWiM6yOfa3PIphViJ/gFPbvidQ+veqSOHci/PxBcDabeUNCzpOODJZig==",
        "name": "http-proxy-agent",
        "url": "https://registry.npmjs.org/http-proxy-agent/-/http-proxy-agent-7.0.2.tgz",
    },
    "https-proxy-agent@7.0.6": {
        "deps": [
            {"id": "agent-base@7.1.4"},
            {"id": "debug@4.4.3-643ed7cc"},
        ],
        "integrity": "sha512-vK9P5/iUfdl95AI+JVyUuIcVtd4ofvtrOr3HNtM2yxC9bnMbEdp3x01OhQNnjb8IJYi38VlTE3mBXwcfvywuSw==",
        "name": "https-proxy-agent",
        "url": "https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-7.0.6.tgz",
    },
    "iconv-lite@0.6.3": {
        "deps": [{"id": "safer-buffer@2.1.2"}],
        "integrity": "sha512-4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==",
        "name": "iconv-lite",
        "url": "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz",
    },
    "imurmurhash@0.1.4": {
        "integrity": "sha512-JmXMZ6wuvDmLiHEml9ykzqO6lwFbof0GG4IkcGaENdCRDDmMVnny7s5HsIgHCbaq0w2MyPhDqkhTUgS2LU2PHA==",
        "name": "imurmurhash",
        "url": "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz",
    },
    "ip-address@10.1.0": {
        "integrity": "sha512-XXADHxXmvT9+CRxhXg56LJovE+bmWnEWB78LB83VZTprKTmaC5QfruXocxzTZ2Kl0DNwKuBdlIhjL8LeY8Sf8Q==",
        "name": "ip-address",
        "url": "https://registry.npmjs.org/ip-address/-/ip-address-10.1.0.tgz",
    },
    "is-core-module@2.16.1": {
        "deps": [{"id": "hasown@2.0.2"}],
        "integrity": "sha512-UfoeMA6fIJ8wTYFEUjelnaGI67v6+N7qXJEvQuIGa99l4xsCruSYOVSQ0uPANn4dAzm8lkYPaKLrrijLq7x23w==",
        "name": "is-core-module",
        "url": "https://registry.npmjs.org/is-core-module/-/is-core-module-2.16.1.tgz",
    },
    "is-module@1.0.0": {
        "integrity": "sha512-51ypPSPCoTEIN9dy5Oy+h4pShgJmPCygKfyRCISBI+JoWT/2oJvK8QPxmwv7b/p239jXrm9M1mlQbyKJ5A152g==",
        "name": "is-module",
        "url": "https://registry.npmjs.org/is-module/-/is-module-1.0.0.tgz",
    },
    "is-reference@1.2.1": {
        "deps": [{"id": "@types/estree@1.0.8"}],
        "integrity": "sha512-U82MsXXiFIrjCK4otLT+o2NA2Cd2g5MLoOVXUZjIOhLurrRxpEXzI8O0KZHr3IjLvlAH1kTPYSuqer5T9ZVBKQ==",
        "name": "is-reference",
        "url": "https://registry.npmjs.org/is-reference/-/is-reference-1.2.1.tgz",
    },
    "isexe@3.1.1": {
        "integrity": "sha512-LpB/54B+/2J5hqQ7imZHfdU31OlgQqx7ZicVlkm9kzg9/w8GKLEcFfJl/t7DCEDueOyBAD6zCCwTO6Fzs0NoEQ==",
        "name": "isexe",
        "url": "https://registry.npmjs.org/isexe/-/isexe-3.1.1.tgz",
    },
    "lru-cache@11.2.4": {
        "integrity": "sha512-B5Y16Jr9LB9dHVkh6ZevG+vAbOsNOYCX+sXvFWFu7B3Iz5mijW3zdbMyhsh8ANd2mSWBYdJgnqi+mL7/LrOPYg==",
        "name": "lru-cache",
        "url": "https://registry.npmjs.org/lru-cache/-/lru-cache-11.2.4.tgz",
    },
    "magic-string@0.30.21": {
        "deps": [{"id": "@jridgewell/sourcemap-codec@1.5.5"}],
        "integrity": "sha512-vd2F4YUyEXKGcLHoq+TEyCjxueSeHnFxyyjNp80yg0XV4vUhnDer/lvvlqM/arB5bXQN5K2/3oinyCRyx8T2CQ==",
        "name": "magic-string",
        "url": "https://registry.npmjs.org/magic-string/-/magic-string-0.30.21.tgz",
    },
    "make-fetch-happen@15.0.3": {
        "deps": [
            {"id": "@npmcli/agent@4.0.0"},
            {"id": "cacache@20.0.3"},
            {"id": "http-cache-semantics@4.2.0"},
            {"id": "minipass-fetch@5.0.0"},
            {"id": "minipass-flush@1.0.5"},
            {"id": "minipass-pipeline@1.2.4"},
            {"id": "minipass@7.1.2"},
            {"id": "negotiator@1.0.0"},
            {"id": "proc-log@6.1.0"},
            {"id": "promise-retry@2.0.1"},
            {"id": "ssri@13.0.0"},
        ],
        "integrity": "sha512-iyyEpDty1mwW3dGlYXAJqC/azFn5PPvgKVwXayOGBSmKLxhKZ9fg4qIan2ePpp1vJIwfFiO34LAPZgq9SZW9Aw==",
        "name": "make-fetch-happen",
        "url": "https://registry.npmjs.org/make-fetch-happen/-/make-fetch-happen-15.0.3.tgz",
    },
    "minimatch@10.1.1": {
        "deps": [{"id": "@isaacs/brace-expansion@5.0.0"}],
        "integrity": "sha512-enIvLvRAFZYXJzkCYG5RKmPfrFArdLv+R+lbQ53BmIMLIry74bjKzX6iHAm8WYamJkhSSEabrWN5D97XnKObjQ==",
        "name": "minimatch",
        "url": "https://registry.npmjs.org/minimatch/-/minimatch-10.1.1.tgz",
    },
    "minipass-collect@2.0.1": {
        "deps": [{"id": "minipass@7.1.2"}],
        "integrity": "sha512-D7V8PO9oaz7PWGLbCACuI1qEOsq7UKfLotx/C0Aet43fCUB/wfQ7DYeq2oR/svFJGYDHPr38SHATeaj/ZoKHKw==",
        "name": "minipass-collect",
        "url": "https://registry.npmjs.org/minipass-collect/-/minipass-collect-2.0.1.tgz",
    },
    "minipass-fetch@5.0.0": {
        "deps": [
            {"id": "encoding@0.1.13"},
            {"id": "minipass-sized@1.0.3"},
            {"id": "minipass@7.1.2"},
            {"id": "minizlib@3.1.0"},
        ],
        "integrity": "sha512-fiCdUALipqgPWrOVTz9fw0XhcazULXOSU6ie40DDbX1F49p1dBrSRBuswndTx1x3vEb/g0FT7vC4c4C2u/mh3A==",
        "name": "minipass-fetch",
        "url": "https://registry.npmjs.org/minipass-fetch/-/minipass-fetch-5.0.0.tgz",
    },
    "minipass-flush@1.0.5": {
        "deps": [{"id": "minipass@3.3.6"}],
        "integrity": "sha512-JmQSYYpPUqX5Jyn1mXaRwOda1uQ8HP5KAT/oDSLCzt1BYRhQU0/hDtsB1ufZfEEzMZ9aAVmsBw8+FWsIXlClWw==",
        "name": "minipass-flush",
        "url": "https://registry.npmjs.org/minipass-flush/-/minipass-flush-1.0.5.tgz",
    },
    "minipass-pipeline@1.2.4": {
        "deps": [{"id": "minipass@3.3.6"}],
        "integrity": "sha512-xuIq7cIOt09RPRJ19gdi4b+RiNvDFYe5JH+ggNvBqGqpQXcru3PcRmOZuHBKWK1Txf9+cQ+HMVN4d6z46LZP7A==",
        "name": "minipass-pipeline",
        "url": "https://registry.npmjs.org/minipass-pipeline/-/minipass-pipeline-1.2.4.tgz",
    },
    "minipass-sized@1.0.3": {
        "deps": [{"id": "minipass@3.3.6"}],
        "integrity": "sha512-MbkQQ2CTiBMlA2Dm/5cY+9SWFEN8pzzOXi6rlM5Xxq0Yqbda5ZQy9sU75a673FE9ZK0Zsbr6Y5iP6u9nktfg2g==",
        "name": "minipass-sized",
        "url": "https://registry.npmjs.org/minipass-sized/-/minipass-sized-1.0.3.tgz",
    },
    "minipass@3.3.6": {
        "deps": [{"id": "yallist@4.0.0"}],
        "integrity": "sha512-DxiNidxSEK+tHG6zOIklvNOwm3hvCrbUrdtzY74U6HKTJxvIDfOUL5W5P2Ghd3DTkhhKPYGqeNUIh5qcM4YBfw==",
        "name": "minipass",
        "url": "https://registry.npmjs.org/minipass/-/minipass-3.3.6.tgz",
    },
    "minipass@7.1.2": {
        "integrity": "sha512-qOOzS1cBTWYF4BH8fVePDBOO9iptMnGUEZwNc/cMWnTV2nVLZ7VoNWEPHkYczZA0pdoA7dl6e7FL659nX9S2aw==",
        "name": "minipass",
        "url": "https://registry.npmjs.org/minipass/-/minipass-7.1.2.tgz",
    },
    "minizlib@3.1.0": {
        "deps": [{"id": "minipass@7.1.2"}],
        "integrity": "sha512-KZxYo1BUkWD2TVFLr0MQoM8vUUigWD3LlD83a/75BqC+4qE0Hb1Vo5v1FgcfaNXvfXzr+5EhQ6ing/CaBijTlw==",
        "name": "minizlib",
        "url": "https://registry.npmjs.org/minizlib/-/minizlib-3.1.0.tgz",
    },
    "ms@2.1.3": {
        "integrity": "sha512-6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==",
        "name": "ms",
        "url": "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz",
    },
    "negotiator@1.0.0": {
        "integrity": "sha512-8Ofs/AUQh8MaEcrlq5xOX0CQ9ypTF5dl78mjlMNfOK08fzpgTHQRQPBxcPlEtIw0yRpws+Zo/3r+5WRby7u3Gg==",
        "name": "negotiator",
        "url": "https://registry.npmjs.org/negotiator/-/negotiator-1.0.0.tgz",
    },
    "node-gyp@12.1.0": {
        "deps": [
            {"id": "env-paths@2.2.1"},
            {"id": "exponential-backoff@3.1.3"},
            {"id": "graceful-fs@4.2.11"},
            {"id": "make-fetch-happen@15.0.3"},
            {"id": "nopt@9.0.0"},
            {"id": "proc-log@6.1.0"},
            {"id": "semver@7.7.3"},
            {"id": "tar@7.5.2"},
            {"id": "tinyglobby@0.2.15"},
            {"id": "which@6.0.0"},
        ],
        "integrity": "sha512-W+RYA8jBnhSr2vrTtlPYPc1K+CSjGpVDRZxcqJcERZ8ND3A1ThWPHRwctTx3qC3oW99jt726jhdz3Y6ky87J4g==",
        "name": "node-gyp",
        "url": "https://registry.npmjs.org/node-gyp/-/node-gyp-12.1.0.tgz",
    },
    "nopt@9.0.0": {
        "deps": [{"id": "abbrev@4.0.0"}],
        "integrity": "sha512-Zhq3a+yFKrYwSBluL4H9XP3m3y5uvQkB/09CwDruCiRmR/UJYnn9W4R48ry0uGC70aeTPKLynBtscP9efFFcPw==",
        "name": "nopt",
        "url": "https://registry.npmjs.org/nopt/-/nopt-9.0.0.tgz",
    },
    "once@1.4.0": {
        "deps": [{"id": "wrappy@1.0.2"}],
        "integrity": "sha512-lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==",
        "name": "once",
        "url": "https://registry.npmjs.org/once/-/once-1.4.0.tgz",
    },
    "p-map@7.0.4": {
        "integrity": "sha512-tkAQEw8ysMzmkhgw8k+1U/iPhWNhykKnSk4Rd5zLoPJCuJaGRPo6YposrZgaxHKzDHdDWWZvE/Sk7hsL2X/CpQ==",
        "name": "p-map",
        "url": "https://registry.npmjs.org/p-map/-/p-map-7.0.4.tgz",
    },
    "path-parse@1.0.7": {
        "integrity": "sha512-LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==",
        "name": "path-parse",
        "url": "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz",
    },
    "path-scurry@2.0.1": {
        "deps": [
            {"id": "lru-cache@11.2.4"},
            {"id": "minipass@7.1.2"},
        ],
        "integrity": "sha512-oWyT4gICAu+kaA7QWk/jvCHWarMKNs6pXOGWKDTr7cw4IGcUbW+PeTfbaQiLGheFRpjo6O9J0PmyMfQPjH71oA==",
        "name": "path-scurry",
        "url": "https://registry.npmjs.org/path-scurry/-/path-scurry-2.0.1.tgz",
    },
    "picomatch@4.0.3": {
        "integrity": "sha512-5gTmgEY/sqK6gFXLIsQNH19lWb4ebPDLA4SdLP7dsWkIXHWlG66oPuVvXSGFPppYZz8ZDZq0dYYrbHfBCVUb1Q==",
        "name": "picomatch",
        "url": "https://registry.npmjs.org/picomatch/-/picomatch-4.0.3.tgz",
    },
    "prettier-plugin-organize-imports@4.3.0-dc3fc578": {
        "deps": [
            {"id": "prettier@3.7.4"},
            {"id": "typescript@5.9.3-d305d436"},
        ],
        "integrity": "sha512-FxFz0qFhyBsGdIsb697f/EkvHzi5SZOhWAjxcx2dLt+Q532bAlhswcXGYB1yzjZ69kW8UoadFBw7TyNwlq96Iw==",
        "name": "prettier-plugin-organize-imports",
        "url": "https://registry.npmjs.org/prettier-plugin-organize-imports/-/prettier-plugin-organize-imports-4.3.0.tgz",
    },
    "prettier@3.7.4": {
        "integrity": "sha512-v6UNi1+3hSlVvv8fSaoUbggEM5VErKmmpGA7Pl3HF8V6uKY7rvClBOJlH6yNwQtfTueNkGVpOv/mtWL9L4bgRA==",
        "name": "prettier",
        "url": "https://registry.npmjs.org/prettier/-/prettier-3.7.4.tgz",
    },
    "proc-log@6.1.0": {
        "integrity": "sha512-iG+GYldRf2BQ0UDUAd6JQ/RwzaQy6mXmsk/IzlYyal4A4SNFw54MeH4/tLkF4I5WoWG9SQwuqWzS99jaFQHBuQ==",
        "name": "proc-log",
        "url": "https://registry.npmjs.org/proc-log/-/proc-log-6.1.0.tgz",
    },
    "promise-retry@2.0.1": {
        "deps": [
            {"id": "err-code@2.0.3"},
            {"id": "retry@0.12.0"},
        ],
        "integrity": "sha512-y+WKFlBR8BGXnsNlIHFGPZmyDf3DFMoLhaflAnyZgV6rG6xu+JwesTo2Q9R6XwYmtmwAFCkAk3e35jEdoeh/3g==",
        "name": "promise-retry",
        "url": "https://registry.npmjs.org/promise-retry/-/promise-retry-2.0.1.tgz",
    },
    "resolve@1.22.11-4e481dbf": {
        "deps": [
            {"id": "is-core-module@2.16.1"},
            {"id": "path-parse@1.0.7"},
            {"id": "supports-preserve-symlinks-flag@1.0.0"},
        ],
        "integrity": "sha512-RfqAvLnMl313r7c9oclB1HhUEAezcpLjz95wFH4LVuhk9JF/r22qmVP9AMmOU4vMX7Q8pN8jwNg/CSpdFnMjTQ==",
        "name": "resolve",
        "url": "https://registry.npmjs.org/resolve/-/resolve-1.22.11.tgz",
    },
    "retry@0.12.0": {
        "integrity": "sha512-9LkiTwjUh6rT555DtE9rTX+BKByPfrMzEAtnlEtdEwr3Nkffwiihqe2bWADg+OQRjt9gl6ICdmB/ZFDCGAtSow==",
        "name": "retry",
        "url": "https://registry.npmjs.org/retry/-/retry-0.12.0.tgz",
    },
    "rollup@4.53.3": {
        "deps": [
            {"id": "@rollup/rollup-android-arm-eabi@4.53.3"},
            {"id": "@rollup/rollup-android-arm64@4.53.3"},
            {"id": "@rollup/rollup-darwin-arm64@4.53.3"},
            {"id": "@rollup/rollup-darwin-x64@4.53.3"},
            {"id": "@rollup/rollup-freebsd-arm64@4.53.3"},
            {"id": "@rollup/rollup-freebsd-x64@4.53.3"},
            {"id": "@rollup/rollup-linux-arm-gnueabihf@4.53.3"},
            {"id": "@rollup/rollup-linux-arm-musleabihf@4.53.3"},
            {"id": "@rollup/rollup-linux-arm64-gnu@4.53.3"},
            {"id": "@rollup/rollup-linux-arm64-musl@4.53.3"},
            {"id": "@rollup/rollup-linux-loong64-gnu@4.53.3"},
            {"id": "@rollup/rollup-linux-ppc64-gnu@4.53.3"},
            {"id": "@rollup/rollup-linux-riscv64-gnu@4.53.3"},
            {"id": "@rollup/rollup-linux-riscv64-musl@4.53.3"},
            {"id": "@rollup/rollup-linux-s390x-gnu@4.53.3"},
            {"id": "@rollup/rollup-linux-x64-gnu@4.53.3"},
            {"id": "@rollup/rollup-linux-x64-musl@4.53.3"},
            {"id": "@rollup/rollup-openharmony-arm64@4.53.3"},
            {"id": "@rollup/rollup-win32-arm64-msvc@4.53.3"},
            {"id": "@rollup/rollup-win32-ia32-msvc@4.53.3"},
            {"id": "@rollup/rollup-win32-x64-gnu@4.53.3"},
            {"id": "@rollup/rollup-win32-x64-msvc@4.53.3"},
            {"id": "@types/estree@1.0.8"},
            {"id": "fsevents@2.3.3-21ad2b13"},
        ],
        "integrity": "sha512-w8GmOxZfBmKknvdXU1sdM9NHcoQejwF/4mNgj2JuEEdRaHwwF12K7e9eXn1nLZ07ad+du76mkVsyeb2rKGllsA==",
        "name": "rollup",
        "url": "https://registry.npmjs.org/rollup/-/rollup-4.53.3.tgz",
    },
    "safer-buffer@2.1.2": {
        "integrity": "sha512-YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==",
        "name": "safer-buffer",
        "url": "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz",
    },
    "semver@7.7.3": {
        "integrity": "sha512-SdsKMrI9TdgjdweUSR9MweHA4EJ8YxHn8DFaDisvhVlUOe4BF1tLD7GAj0lIqWVl+dPb/rExr0Btby5loQm20Q==",
        "name": "semver",
        "url": "https://registry.npmjs.org/semver/-/semver-7.7.3.tgz",
    },
    "smart-buffer@4.2.0": {
        "integrity": "sha512-94hK0Hh8rPqQl2xXc3HsaBoOXKV20MToPkcXvwbISWLEs+64sBq5kFgn2kJDHb1Pry9yrP0dxrCI9RRci7RXKg==",
        "name": "smart-buffer",
        "url": "https://registry.npmjs.org/smart-buffer/-/smart-buffer-4.2.0.tgz",
    },
    "socks-proxy-agent@8.0.5": {
        "deps": [
            {"id": "agent-base@7.1.4"},
            {"id": "debug@4.4.3-643ed7cc"},
            {"id": "socks@2.8.7"},
        ],
        "integrity": "sha512-HehCEsotFqbPW9sJ8WVYB6UbmIMv7kUUORIF2Nncq4VQvBfNBLibW9YZR5dlYCSUhwcD628pRllm7n+E+YTzJw==",
        "name": "socks-proxy-agent",
        "url": "https://registry.npmjs.org/socks-proxy-agent/-/socks-proxy-agent-8.0.5.tgz",
    },
    "socks@2.8.7": {
        "deps": [
            {"id": "ip-address@10.1.0"},
            {"id": "smart-buffer@4.2.0"},
        ],
        "integrity": "sha512-HLpt+uLy/pxB+bum/9DzAgiKS8CX1EvbWxI4zlmgGCExImLdiad2iCwXT5Z4c9c3Eq8rP2318mPW2c+QbtjK8A==",
        "name": "socks",
        "url": "https://registry.npmjs.org/socks/-/socks-2.8.7.tgz",
    },
    "ssri@13.0.0": {
        "deps": [{"id": "minipass@7.1.2"}],
        "integrity": "sha512-yizwGBpbCn4YomB2lzhZqrHLJoqFGXihNbib3ozhqF/cIp5ue+xSmOQrjNasEE62hFxsCcg/V/z23t4n8jMEng==",
        "name": "ssri",
        "url": "https://registry.npmjs.org/ssri/-/ssri-13.0.0.tgz",
    },
    "supports-preserve-symlinks-flag@1.0.0": {
        "integrity": "sha512-ot0WnXS9fgdkgIcePe6RHNk1WA8+muPa6cSjeR3V8K27q9BB1rTE3R1p7Hv0z1ZyAc8s6Vvv8DIyWf681MAt0w==",
        "name": "supports-preserve-symlinks-flag",
        "url": "https://registry.npmjs.org/supports-preserve-symlinks-flag/-/supports-preserve-symlinks-flag-1.0.0.tgz",
    },
    "tar@7.5.2": {
        "deps": [
            {"id": "@isaacs/fs-minipass@4.0.1"},
            {"id": "chownr@3.0.0"},
            {"id": "minipass@7.1.2"},
            {"id": "minizlib@3.1.0"},
            {"id": "yallist@5.0.0"},
        ],
        "integrity": "sha512-7NyxrTE4Anh8km8iEy7o0QYPs+0JKBTj5ZaqHg6B39erLg0qYXN3BijtShwbsNSvQ+LN75+KV+C4QR/f6Gwnpg==",
        "name": "tar",
        "url": "https://registry.npmjs.org/tar/-/tar-7.5.2.tgz",
    },
    "tinyglobby@0.2.15": {
        "deps": [
            {"id": "fdir@6.5.0-0e783aad"},
            {"id": "picomatch@4.0.3"},
        ],
        "integrity": "sha512-j2Zq4NyQYG5XMST4cbs02Ak8iJUdxRM0XI5QyxXuZOzKOINmWurp3smXu3y5wDcJrptwpSjgXHzIQxR0omXljQ==",
        "name": "tinyglobby",
        "url": "https://registry.npmjs.org/tinyglobby/-/tinyglobby-0.2.15.tgz",
    },
    "tunnel@0.0.6": {
        "integrity": "sha512-1h/Lnq9yajKY2PEbBadPXj3VxsDDu844OnaAo52UVmIzIvwwtBPIuNvkjuzBlTWpfJyUbG3ez0KSBibQkj4ojg==",
        "name": "tunnel",
        "url": "https://registry.npmjs.org/tunnel/-/tunnel-0.0.6.tgz",
    },
    "typescript@5.9.3-d305d436": {
        "integrity": "sha512-jl1vZzPDinLr9eUt3J/t7V6FgNEw9QjvBPdysz9KfQDD41fQrC2Y4vKQdiaUpFT4bXlb1RHhLpp8wtm6M5TgSw==",
        "name": "typescript",
        "url": "https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz",
    },
    "undici-types@7.16.0": {
        "integrity": "sha512-Zz+aZWSj8LE6zoxD+xrjh4VfkIG8Ya6LvYkZqtUQGJPZjYl53ypCaUwWqo7eI0x66KBGeRo+mlBEkMSeSZ38Nw==",
        "name": "undici-types",
        "url": "https://registry.npmjs.org/undici-types/-/undici-types-7.16.0.tgz",
    },
    "undici@5.29.0": {
        "deps": [{"id": "@fastify/busboy@2.1.1"}],
        "integrity": "sha512-raqeBD6NQK4SkWhQzeYKd1KmIG6dllBOTt55Rmkt4HtI9mwdWtJljnrXjAFUBLTSN67HWrOIZ3EPF4kjUw80Bg==",
        "name": "undici",
        "url": "https://registry.npmjs.org/undici/-/undici-5.29.0.tgz",
    },
    "unique-filename@5.0.0": {
        "deps": [{"id": "unique-slug@6.0.0"}],
        "integrity": "sha512-2RaJTAvAb4owyjllTfXzFClJ7WsGxlykkPvCr9pA//LD9goVq+m4PPAeBgNodGZ7nSrntT/auWpJ6Y5IFXcfjg==",
        "name": "unique-filename",
        "url": "https://registry.npmjs.org/unique-filename/-/unique-filename-5.0.0.tgz",
    },
    "unique-slug@6.0.0": {
        "deps": [{"id": "imurmurhash@0.1.4"}],
        "integrity": "sha512-4Lup7Ezn8W3d52/xBhZBVdx323ckxa7DEvd9kPQHppTkLoJXw6ltrBCyj5pnrxj0qKDxYMJ56CoxNuFCscdTiw==",
        "name": "unique-slug",
        "url": "https://registry.npmjs.org/unique-slug/-/unique-slug-6.0.0.tgz",
    },
    "universal-user-agent@6.0.1": {
        "integrity": "sha512-yCzhz6FN2wU1NiiQRogkTQszlQSlpWaw8SvVegAc+bDxbzHgh1vX8uIe8OYyMH6DwH+sdTJsgMl36+mSMdRJIQ==",
        "name": "universal-user-agent",
        "url": "https://registry.npmjs.org/universal-user-agent/-/universal-user-agent-6.0.1.tgz",
    },
    "universal-user-agent@7.0.3": {
        "integrity": "sha512-TmnEAEAsBJVZM/AADELsK76llnwcf9vMKuPz8JflO1frO8Lchitr0fNaN9d+Ap0BjKtqWqd/J17qeDnXh8CL2A==",
        "name": "universal-user-agent",
        "url": "https://registry.npmjs.org/universal-user-agent/-/universal-user-agent-7.0.3.tgz",
    },
    "which@6.0.0": {
        "deps": [{"id": "isexe@3.1.1"}],
        "integrity": "sha512-f+gEpIKMR9faW/JgAgPK1D7mekkFoqbmiwvNzuhsHetni20QSgzg9Vhn0g2JSJkkfehQnqdUAx7/e15qS1lPxg==",
        "name": "which",
        "url": "https://registry.npmjs.org/which/-/which-6.0.0.tgz",
    },
    "wrappy@1.0.2": {
        "integrity": "sha512-l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==",
        "name": "wrappy",
        "url": "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz",
    },
    "yallist@4.0.0": {
        "integrity": "sha512-3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==",
        "name": "yallist",
        "url": "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz",
    },
    "yallist@5.0.0": {
        "integrity": "sha512-YgvUTfwqyc7UXVMrB+SImsVYSmTS8X/tSrtdNZMImM+n7+QTriRXyXim0mBrTXNeqzVF0KWGgHPeiyViFFrNDw==",
        "name": "yallist",
        "url": "https://registry.npmjs.org/yallist/-/yallist-5.0.0.tgz",
    },
}

ROOTS = [
    {
        "id": "@actions/core@2.0.1",
        "name": "@actions/core",
    },
    {
        "id": "@actions/github@6.0.1",
        "name": "@actions/github",
    },
    {
        "id": "@js-joda/core@5.6.5",
        "name": "@js-joda/core",
    },
    {
        "id": "@octokit/rest@22.0.1",
        "name": "@octokit/rest",
    },
    {
        "id": "@rollup/plugin-commonjs@29.0.0-dc3fc578",
        "name": "@rollup/plugin-commonjs",
    },
    {
        "id": "@rollup/plugin-json@6.1.0-dc3fc578",
        "name": "@rollup/plugin-json",
    },
    {
        "id": "@rollup/plugin-node-resolve@16.0.3-dc3fc578",
        "name": "@rollup/plugin-node-resolve",
    },
    {
        "id": "@types/node@24.10.4",
        "name": "@types/node",
    },
    {
        "id": "prettier-plugin-organize-imports@4.3.0-dc3fc578",
        "name": "prettier-plugin-organize-imports",
    },
    {
        "id": "prettier@3.7.4",
        "name": "prettier",
    },
    {
        "id": "rollup@4.53.3",
        "name": "rollup",
    },
    {
        "id": "typescript@5.9.3-d305d436",
        "name": "typescript",
    },
]
